require "../spec_helper"

# Verify PG DDL emission. No live database required — these specs check
# the SQL strings the adapter would issue against PostgreSQL.

private class PgUser < Prostore::Model
  field 1, :id, Int64, primary: true, auto_increment: true
  field 2, :email, String
  field 3, :tenant_id, Int64
  field 4, :score, Int32?

  index 1, [:email], unique: true

  query :by_email, ->(e : String) { where(email: e) }
  query :by_tenant, ->(t : Int64) { where(tenant_id: t) }
end

describe "PostgreSQL DDL emission" do
  it "renders identity columns for auto_increment" do
    sql = Prostore::Adapter::Postgres::DDL.render_create_table(
      PgUser.prostore_schema,
      {"pg_user" => ["id"]}
    )
    sql.should contain("BIGINT GENERATED BY DEFAULT AS IDENTITY")
    sql.should contain("PRIMARY KEY")
  end

  it "uses portable PG types" do
    sql = Prostore::Adapter::Postgres::DDL.render_create_table(
      PgUser.prostore_schema,
      {"pg_user" => ["id"]}
    )
    sql.should contain("TEXT")
    sql.should contain("BIGINT")
    sql.should contain("INTEGER")
  end

  it "renders unique indexes" do
    idx = PgUser.prostore_schema.indexes.first
    sql = Prostore::Adapter::Postgres::DDL.render_create_index("pg_user", idx)
    sql.should contain("UNIQUE INDEX")
    sql.should contain("\"email\"")
  end

  it "exposes correct capability flags" do
    db = DB.open("sqlite3::memory:") # any DB to construct the adapter
    adapter = Prostore::Adapter::Postgres::Adapter.new(db, "postgres://localhost/test")
    adapter.supports_alter_set_not_null?.should be_true
    adapter.supports_add_constraint_not_valid?.should be_true
    adapter.supports_alter_drop_column?.should be_true
    db.close
  end

  it "rejects unsupported portable types in column_type" do
    expect_raises(Prostore::SchemaError, /No PostgreSQL type/) do
      Prostore::Adapter::Postgres.column_type("nonexistent")
    end
  end

  it "rejects auto_increment on non-integer in identity_type" do
    expect_raises(Prostore::SchemaError, /requires Int32 or Int64/) do
      Prostore::Adapter::Postgres.identity_type("string")
    end
  end
end
