require "../../schema"
require "./types"

module Prostore
  module Adapter
    module Postgres
      # PostgreSQL DDL builders (ADR-0014). Mirrors SQLite::DDL but emits PG
      # idiomatic syntax: GENERATED BY DEFAULT AS IDENTITY, real BOOLEAN,
      # ALTER TABLE ADD CONSTRAINT, etc.
      module DDL
        extend self

        def quote_ident(name : String) : String
          %("#{name.gsub(%("), %(""))}")
        end

        def quote_string(s : String) : String
          %('#{s.gsub(%('), %(''))}')
        end

        def render_action(action : Symbol) : String
          case action
          when :no_action   then "NO ACTION"
          when :restrict    then "RESTRICT"
          when :cascade     then "CASCADE"
          when :set_null    then "SET NULL"
          when :set_default then "SET DEFAULT"
          else                   raise Prostore::SchemaError.new("unknown FK action: #{action}")
          end
        end

        def render_column(field : Schema::Field) : String
          parts = [quote_ident(field.name)] of String

          if field.primary && field.auto_increment
            parts << Postgres.identity_type(field.portable_type)
            parts << "GENERATED BY DEFAULT AS IDENTITY"
            parts << "PRIMARY KEY"
          else
            parts << Postgres.column_type(field.portable_type)
            parts << "PRIMARY KEY" if field.primary
          end

          parts << "NOT NULL" unless field.nullable

          if sql = field.default_sql
            parts << "DEFAULT (#{sql})"
          end

          parts.join(' ')
        end

        def render_foreign_key_clause(fk : Schema::ForeignKey, target_pk_columns : Array(String)) : String
          ref_cols = fk.references_columns.empty? ? target_pk_columns : fk.references_columns
          src = fk.columns.map { |col| quote_ident(col) }.join(", ")
          tgt = ref_cols.map { |col| quote_ident(col) }.join(", ")

          "CONSTRAINT #{quote_ident(fk.name)} FOREIGN KEY (#{src}) " \
          "REFERENCES #{quote_ident(fk.references_table)} (#{tgt}) " \
          "ON DELETE #{render_action(fk.on_delete)} " \
          "ON UPDATE #{render_action(fk.on_update)}"
        end

        def render_create_table(definition : Schema::Definition,
                                pk_lookup : Hash(String, Array(String))) : String
          io = IO::Memory.new
          io << "CREATE TABLE " << quote_ident(definition.table_name) << " (\n"
          parts = [] of String
          definition.fields.sort_by(&.tag).each do |field|
            parts << "  " + render_column(field)
          end
          definition.foreign_keys.sort_by(&.tag).each do |fk|
            target_pk = pk_lookup[fk.references_table]? ||
                        raise Prostore::SchemaError.new(
                          "Foreign key #{fk.tag} references unknown table #{fk.references_table}")
            parts << "  " + render_foreign_key_clause(fk, target_pk)
          end
          io << parts.join(",\n") << "\n)"
          io.to_s
        end

        def render_create_index(table : String, idx : Schema::Index, concurrently : Bool = false) : String
          io = IO::Memory.new
          io << "CREATE "
          io << "UNIQUE " if idx.unique
          io << "INDEX "
          io << "CONCURRENTLY " if concurrently
          # IF NOT EXISTS makes retry on a partially-created index safe;
          # if a previous CONCURRENTLY left an INVALID index behind, the
          # Steps executor drops it before this runs.
          io << "IF NOT EXISTS " << quote_ident(idx.name)
          io << " ON " << quote_ident(table) << " ("
          io << idx.columns.map { |col| quote_ident(col) }.join(", ")
          io << ')'
          if where = idx.where_sql
            io << " WHERE " << where
          end
          io.to_s
        end
      end
    end
  end
end
