module Prostore
  module Adapter
    module Postgres
      # Portable type → PostgreSQL column type (ADR-0014).
      MAPPING = {
        "int32"   => "INTEGER",
        "int64"   => "BIGINT",
        "float32" => "REAL",
        "float64" => "DOUBLE PRECISION",
        "string"  => "TEXT",
        "bool"    => "BOOLEAN",
        "time"    => "TIMESTAMP WITH TIME ZONE",
        "bytes"   => "BYTEA",
        "uuid"    => "UUID",
        "decimal" => "NUMERIC",
        "json"    => "JSONB",
      }

      def self.column_type(portable : String) : String
        # Arrays of primitives → JSONB on Postgres. Native PG arrays
        # (e.g. INTEGER[]) are deferred — JSONB gives us a uniform IO path
        # at the cost of native array indexing.
        return "JSONB" if portable.starts_with?("array_")
        MAPPING[portable]? ||
          raise Prostore::SchemaError.new("No PostgreSQL type for portable '#{portable}'")
      end

      # The PG type used as IDENTITY column. ADR-0013 specifies
      # GENERATED BY DEFAULT AS IDENTITY.
      def self.identity_type(portable : String) : String
        case portable
        when "int32" then "INTEGER"
        when "int64" then "BIGINT"
        else
          raise Prostore::SchemaError.new(
            "auto_increment requires Int32 or Int64 (ADR-0013), got #{portable}"
          )
        end
      end
    end
  end
end
